### ISSUE TITLE
The results are different from those of ABC tool

### ISSUE THREAD

**Issue by hemingxiao-3** [krzhu/abc_py#5]
Hello, I have recently encountered an issue while using this project. The numAnd and lev synthesized by abc_py seem to differ from the results obtained by the ABC tool. The specific details are as follows:
![Screenshot from 2024-12-17 21-37-40](https://github.com/user-attachments/assets/d2b92720-d27d-4730-95ef-295f05d418c9)
![image](https://github.com/user-attachments/assets/f76778e2-abae-4468-b822-1bcff4a9b43e)
![image](https://github.com/user-attachments/assets/3eee46ab-4805-4b98-87c4-650931b569f9)

**Comment by krzhu** [comment]
maybe it is because if the default parameters are different. See https://github.com/krzhu/abc_py/blob/5a51078ff82ad80a9d1f05714e488edcc9fe56d6/src/interface/AbcInterface.h#L222

This project is just a wrapper for ABC. You can check the cpp to see how it called ABC. It is just sending the command to ABC. Nothing else.
